Hotplate data processing

#rearrange everything & normality tests
```{r}
library(tidyr)
library(dplyr)
library(tidyverse)
library(stats)


female_path <- "hotplatepilot/raw_female_7dayhotplatepilot_48.csv"
male_path <- "hotplatepilot/raw_male_7dayhotplatepilot_48.csv"

output_path <- "hotplatepilot/dummy"

#female data

#read it in
female_data <- read.csv(file = female_path)

#identify only the averages across all 3 von frey measurements
averages <- grep("ave", names(female_data), value = TRUE)
#then keep only those averages plus the animal id
female_data <- female_data[, c("animal",averages), drop = FALSE]

#save it
write.csv(female_data, file = paste0(output_path,"/female_PRISM_horizontal.csv"))

#transpose data so that it is in the prism format
female_data <- as.data.frame(t(female_data))

#fix the column names
colnames(female_data) <- female_data[1,]
female_data <- female_data[-1,]

write.csv(female_data, file = paste0(output_path,"/female_PRISM_vertical.csv"))


#transpose back for animal averaging
female_data <- as.data.frame(t(female_data))

#reassign animal/row names to be in a simple number order
new_row_names <- character(nrow(female_data))
current_number <- 0
current_letter <- "R"

# Loop through the rows and set the new row names
for (i in 1:nrow(female_data)) {
  new_row_names[i] <- paste0(current_number, "_", current_letter)
  
  # Update the number and letter for the next row
  if (i %% 2 == 0) {
    current_number <- current_number + 1
  }
  current_letter <- ifelse(current_letter == "R", "L", "R")
}

# Assign the new row names to the DataFrame
rownames(female_data) <- new_row_names


#create list of all unique animal IDs
female_animals <- sub("^(.*?)_.*", "\\1", rownames(female_data))
female_animals <- unique(female_animals)

female_data[] <- lapply(female_data, as.numeric)



# Preallocate the 'final' DataFrame with dimensions
final_females <- data.frame(matrix(NA, nrow = length(female_animals), ncol = ncol(female_data)))
colnames(final_females) <- colnames(female_data)
rownames(final_females) <- female_animals

# Loop through the identifiers
for (i in seq_along(female_animals)) {
  id <- female_animals[i]

  # Subset df to keep rows with row names containing the identifier
  subset_df <- female_data[grep(id, rownames(female_data)), ]

  # Calculate the row-wise means for each subset and assign to 'final'
  final_females[i, ] <- colMeans(subset_df)
}

write.csv(final_females, file = paste0(output_path,"/ave_female_PRISM_horizontal.csv"))

#Normality test

shapiro_test_row <- function(row) {
  result <- shapiro.test(row)
  return(result$p.value)
}

# Apply the Shapiro-Wilk test to each row of your DataFrame
shapiro_test_results <- apply(final_females, 1, shapiro_test_row)

shapiro_frame <- data.frame("p_values" = shapiro_test_results)
rownames(shapiro_frame) <- rownames(final_females)
shapiro_frame <- shapiro_frame %>%
  mutate(sig = ifelse(p_values < 0.05, "*", ""))

write.csv(shapiro_frame, file = paste0(output_path,"/normality_females.csv"))

#transpose averaged data
final_females <- as.data.frame(t(final_females))

write.csv(final_females, file = paste0(output_path,"/ave_female_PRISM_vertical.csv"))





##############################

#male data

#read it in
male_data <- read.csv(file = male_path)

#identify only the averages across all 3 von frey measurements
averages <- grep("ave", names(male_data), value = TRUE)
#then keep only those averages plus the animal id
male_data <- male_data[, c("animal",averages), drop = FALSE]

#save it
write.csv(male_data, file = paste0(output_path,"/male_PRISM_horizontal.csv"))

#transpose data so that it is in the prism format
male_data <- as.data.frame(t(male_data))

#fix the column names
colnames(male_data) <- male_data[1,]
male_data <- male_data[-1,]

write.csv(male_data, file = paste0(output_path,"/male_PRISM_vertical.csv"))


#transpose back for animal averaging
male_data <- as.data.frame(t(male_data))

#reassign animal/row names to be in a simple number order
new_row_names <- character(nrow(male_data))
current_number <- 0
current_letter <- "R"

# Loop through the rows and set the new row names
for (i in 1:nrow(male_data)) {
  new_row_names[i] <- paste0(current_number, "_", current_letter)
  
  # Update the number and letter for the next row
  if (i %% 2 == 0) {
    current_number <- current_number + 1
  }
  current_letter <- ifelse(current_letter == "R", "L", "R")
}

# Assign the new row names to the DataFrame
rownames(male_data) <- new_row_names


#create list of all unique animal IDs
male_animals <- sub("^(.*?)_.*", "\\1", rownames(male_data))
male_animals <- unique(male_animals)

male_data[] <- lapply(male_data, as.numeric)



# Preallocate the 'final' DataFrame with dimensions
final_males <- data.frame(matrix(NA, nrow = length(male_animals), ncol = ncol(male_data)))
colnames(final_males) <- colnames(male_data)
rownames(final_males) <- male_animals

# Loop through the identifiers
for (i in seq_along(male_animals)) {
  id <- male_animals[i]

  # Subset df to keep rows with row names containing the identifier
  subset_df <- male_data[grep(id, rownames(male_data)), ]

  # Calculate the row-wise means for each subset and assign to 'final'
  final_males[i, ] <- colMeans(subset_df)
}

write.csv(final_males, file = paste0(output_path,"/ave_male_PRISM_horizontal.csv"))

#Normality test

# Apply the Shapiro-Wilk test to each row of your DataFrame
shapiro_test_results <- apply(final_males, 1, shapiro_test_row)

shapiro_frame <- data.frame("p_values" = shapiro_test_results)
rownames(shapiro_frame) <- rownames(final_males)

shapiro_frame <- shapiro_frame %>%
  mutate(sig = ifelse(p_values < 0.05, "*", ""))

write.csv(shapiro_frame, file = paste0(output_path,"/normality_males.csv"))

#transpose averaged data
final_males <- as.data.frame(t(final_males))

write.csv(final_males, file = paste0(output_path,"/ave_male_PRISM_vertical.csv"))


```
#mixed effects stuff
```{r}
#for the lme4 stuff, the data needs to be in a longer format so we'll do that for each sex, then combine them


#pivot the female data longer
long_females <- pivot_longer(
  data = final_females,
  cols = everything(),
  names_to = "animal",
  values_to = "averages"
)

#rearrange
long_females$animal <- as.numeric(long_females$animal)
long_females <- long_females %>%
  arrange(animal)

#add in a sex column
long_females$sex <- "female"


#get the number of female and male animals
female_length <- as.numeric(length(female_animals))
male_length <- as.numeric(length(male_animals))

#create a new sequence for the males so that each animal has a unique number.  The females keep theirs, and we'll reassign the male numbers picking up at the last female number as it is currently
new_male_sequence <- as.character(seq(from = female_length, to = (male_length+female_length)-1, by = 1))



#create the new dataframe
long_males <- final_males
#but first reassign the male animal names (simply the columns)
colnames(long_males) <- new_male_sequence

#now we can pivot that longer
long_males <- pivot_longer(
  data = long_males,
  cols = everything(),
  names_to = "animal",
  values_to = "averages"
)

#samae thing, some rearranging here
long_males$animal <- as.numeric(long_males$animal)
long_males <- long_males %>%
  arrange(animal)

#add on the sex
long_males$sex <- "male"

#finally combine everything into 1 long dataframe
total_long_data <- rbind(long_females,long_males)




############################
#mixed model code here on

#this order of library loading is important so that it forces p values
library (lme4)
library(lmerTest)


model <- lmer(averages ~ sex + (1|animal), data = total_long_data)

# Display model summary
summary(model)


```

#power analysis

```{r}
#specifically from pilot data

library(pwr)


#females
pwr.anova.test(k = 15, n = NULL, f = 0.5745, sig.level = 0.05, power = 0.8)

#males
pwr.anova.test(k = 15, n = NULL, f = 0.2433, sig.level = 0.05, power = 0.8)

```



#normalization of data
```{r}
#females first

#transpose data back to horizontal format
final_females <- as.data.frame(t(final_females))

norm_females <- data.frame(matrix(NA, nrow = length(female_animals), ncol = ncol(final_females)))
colnames(norm_females) <- colnames(final_females)
rownames(norm_females) <- female_animals

# Loop through the identifiers
for (i in seq_along(female_animals)) {
  id <- female_animals[i]

  # Subset df to keep rows with row names containing the identifier
  subset_df <- final_females[row.names(final_females) == id, ]

  #get the baseline value, which is the first cell, ie day 1, ie baseline
  norm_value <- subset_df[1,1]
  
  #then subtract that value from everything and put it in the placeholder
  norm_females[i, ] <- subset_df - norm_value
}

#get rid of the baseline data, which is now just 0
norm_females <- norm_females[,-1]

write.csv(norm_females, file = paste0(output_path,"/norm_females_horizontal.csv"))

norm_females <- as.data.frame(t(norm_females))

write.csv(norm_females, file = paste0(output_path,"/norm_females_vertical.csv"))



#males
#transpose data back to horizontal format
final_males <- as.data.frame(t(final_males))

norm_males <- data.frame(matrix(NA, nrow = length(male_animals), ncol = ncol(final_males)))
colnames(norm_males) <- colnames(final_males)
rownames(norm_males) <- male_animals


# Loop through the identifiers
for (i in seq_along(male_animals)) {
  id <- male_animals[i]

  # Subset df to keep rows with row names containing the identifier
  subset_df <- final_males[row.names(final_males) == id, ]

  #get the baseline value, which is the first cell, ie day 1, ie baseline
  norm_value <- subset_df[1,1]
  
  #then subtract that value from everything and put it in the placeholder
  norm_males[i, ] <- subset_df - norm_value
}

#get rid of the baseline data, which is now just 0
norm_males <- norm_males[,-1]

write.csv(norm_males, file = paste0(output_path,"/norm_males_horizontal.csv"))

norm_males <- as.data.frame(t(norm_males))

write.csv(norm_males, file = paste0(output_path,"/norm_males_vertical.csv"))

```



